---
 - hosts: webserver
   become: true
   tasks:
      - name: install nginx
        apt: name=nginx state=present update_cache=yes
      - name: install mc
        apt: name=mc state=present update_cache=yes
